server:
  port: 9192

#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
# 
#spring:
#  application:
#    name: USER-SERVICE

#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: donrahman6@gmail.com
#    password: ovybjgyepomeyeen
#    properties:
#      mail:
#        smtp:
#          auth: true
#        starttls:
#          enable: true
#          required: true


